let listings=[];let previousSnapshot=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>n==null?'—':n.toLocaleString('zh-TW')+'萬';
const range=(v,s)=>s==='all'||(v!=null&&((v>=+s.split('-')[0])&&(v<=+s.split('-')[1])));
function fillSelect(id,items){$(id).innerHTML='<option value="all">全部</option>'+[...new Set(items)].filter(Boolean).map(x=>`<option>${x}</option>`).join('')}
function sortData(a){const s=$('#sortFilter').value;return [...a].sort((x,y)=>s==='priceAsc'?(x.price||0)-(y.price||0):s==='priceDesc'?(y.price||0)-(x.price||0):s==='unitAsc'?(x.unit||999)-(y.unit||999):s==='unitDesc'?(y.unit||0)-(x.unit||0):s==='updatedDesc'?y.updated.localeCompare(x.updated):(x.community+y.block).localeCompare(y.community+x.block,'zh-Hant')||(y.floor||-1)-(x.floor||-1))}
function filters(){const k=$('#keyword').value.trim().toLowerCase(),b=$('#buildingFilter').value,bl=$('#blockFilter').value,p=$('#priceFilter').value,a=$('#areaFilter').value,l=$('#layoutFilter').value,pk=$('#parkingFilter').value;return listings.filter(x=>(!k||[x.community,x.block,x.layout,x.id].join(' ').toLowerCase().includes(k))&&(b==='all'||x.community===b)&&(bl==='all'||x.block===bl)&&range(x.price,p)&&range(x.area,a)&&(l==='all'||(x.layout||'').startsWith(l))&&(pk==='all'||(pk==='yes'?x.parking:!x.parking)))}
function card(x){const names=['591','信義','樂居','樂屋','中信','永慶'];const yq=x.yq===true;return `<article class="listing-card" data-id="${x.id}"><div class="listing-top"><div><div class="listing-title">${x.community}｜${x.block} ${x.floor?x.floor+'F':'樓層待確認'}</div><div class="listing-sub">${x.area??'—'}坪 · ${x.layout||'—'} · ${x.parking?'有車位':'無車位'}</div></div><div>${x.new?'<span class="new">🆕 新增</span>':''}${x.yq===false?'<span class="dev-badge">永慶無</span>':yq?'<span class="dev-badge">永慶有</span>':'<span class="dev-badge">永慶待確認</span>'}</div></div><div class="price">${money(x.price)} <span class="unit">${x.unit?x.unit+'萬/坪':'單價待核實'}</span></div><div class="facts"><div>樓層<b>${x.floor?x.floor+'/'+x.totalFloor+'F':'待確認'}</b></div><div>坪數<b>${x.area??'—'}坪</b></div><div>來源<b>${x.sourceVerified||'—'}</b></div></div><div class="platforms">${names.map(p=>`<span class="platform ${x.sources?.[p]?'':'off'}">${p} ${x.sources?.[p]?'●':'○'}</span>`).join('')}</div></article>`}
function render(){const d=sortData(filters());$('#resultCount').textContent=d.length+' 筆案件';$('#listingGrid').innerHTML=d.map(card).join('')||'<div class="card">沒有符合條件的案件。</div>';$$('.listing-card').forEach(e=>e.onclick=()=>detail(listings.find(x=>x.id===e.dataset.id)))}
function detail(x){const links=Object.entries(x.links||{}).map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener">${n}</a>`).join('');$('#detailContent').innerHTML=`<div class="detail"><span class="tag">真實資料</span><h2>${x.community}｜${x.block} ${x.floor?x.floor+'F':'樓層待確認'}</h2><p>資料核實來源：${x.sourceVerified||'—'}　｜　最後核實：${x.updated}</p><div class="detail-grid"><div><b>總價</b>${money(x.price)}</div><div><b>單價</b>${x.unit?x.unit+'萬/坪':'待核實'}</div><div><b>坪數</b>${x.area??'—'}坪</div><div><b>格局</b>${x.layout||'—'}</div><div><b>樓層</b>${x.floor?x.floor+'/'+x.totalFloor+'F':'待確認'}</div><div><b>車位</b>${x.parking?'有':'無'}</div></div><h3>來源</h3><div class="source-links">${links}</div><p class="muted">永慶狀態：${x.yq===true?'已確認有刊登':x.yq===false?'已確認無刊登':'尚未完成交叉核實，暫不列入開發判斷'}</p></div>`;$('#detailDialog').showModal()}
function changeItem(x,type){if(type==='gone')return `<div class="change-item"><strong>⚠️ ${x.community}｜${x.block}</strong><small>${x.area||'—'}坪｜${money(x.price)}｜可能下架／售出</small></div>`;return `<div class="change-item"><strong>${type==='new'?'🆕':'💰'} ${x.community}｜${x.block}</strong><small>${x.area||'—'}坪｜${type==='new'?money(x.price):'價格變更'}</small></div>`}
function renderChanges(){const news=listings.filter(x=>x.new),drops=listings.filter(x=>x.history?.length>1&&x.history[0].price<x.history[1].price);$('#changeNewCount').textContent=news.length;$('#changeDropCount').textContent=drops.length;$('#changeGoneCount').textContent=previousSnapshot.length;$('#newChanges').innerHTML=news.map(x=>changeItem(x,'new')).join('')||'<div class="muted">目前沒有已核實的今日新增。</div>';$('#dropChanges').innerHTML=drops.map(x=>changeItem(x,'drop')).join('')||'<div class="muted">目前沒有已核實的降價歷史。</div>';$('#goneChanges').innerHTML=previousSnapshot.map(x=>changeItem(x,'gone')).join('')||'<div class="muted">尚未建立前一日快照。</div>';$('#historyTable').innerHTML='<div class="muted">價格歷史會在每日快照建立後自動累積；目前第一批真實資料以「初始快照」方式匯入，未虛構歷史價格。</div>'}
function renderDevelop(){const eligible=listings.filter(x=>x.yq===false);const f=$('#developFilter').value;let d=f==='owner'?eligible.filter(x=>x.owner):f==='competitor'?eligible.filter(x=>!x.owner):eligible;$('#developTotal').textContent=eligible.length;$('#ownerCount').textContent=eligible.filter(x=>x.owner).length;$('#noYQCount').textContent=eligible.length;$('#developGrid').innerHTML=d.map(card).join('')||'<div class="muted">目前沒有「已確認永慶無刊登」的案件。</div>';$$('#developGrid .listing-card').forEach(e=>e.onclick=()=>detail(listings.find(x=>x.id===e.dataset.id)))}
async function init(){try{listings=await fetch('data/listings.json',{cache:'no-store'}).then(r=>r.json());}catch(e){$('#listingGrid').innerHTML='<div class="card">資料讀取失敗，請確認 GitHub Pages 已發布。</div>';return}fillSelect('#buildingFilter',listings.map(x=>x.community));fillSelect('#blockFilter',listings.map(x=>x.block));$('#lastUpdated').textContent='最後核實：2026/09/01';$('#statTotal').textContent=listings.length;$('#statNew').textContent=listings.filter(x=>x.new).length;$('#statDrops').textContent=0;$('#statPlatforms').textContent=6;render()}
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+t.dataset.view).classList.add('active');if(t.dataset.view==='changes')renderChanges();if(t.dataset.view==='develop')renderDevelop()});
['#keyword','#buildingFilter','#blockFilter','#priceFilter','#areaFilter','#layoutFilter','#parkingFilter','#sortFilter'].forEach(s=>$(s).addEventListener('input',render));$('#resetFilters').onclick=()=>{$('#keyword').value='';['#buildingFilter','#blockFilter','#priceFilter','#areaFilter','#layoutFilter','#parkingFilter','#sortFilter'].forEach(s=>$(s).value='all');render()};$('#developFilter').onchange=renderDevelop;$('#dialogClose').onclick=()=>$('#detailDialog').close();init();
